% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
% 1) Export the required variables from pdetool and create a MATLAB script
%    to perform operations on these.
% 2) Define the problem completely using a MATLAB script. See
%    https://www.mathworks.com/help/pde/examples.html for examples
%    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',1);
set(ax,'DataAspectRatio',[1 1.5 1]);
set(ax,'PlotBoxAspectRatio',[3 2 1]);
set(ax,'XLim',[-3 3]);
set(ax,'YLim',[-3 3]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pderect([-2 2 2 -2],'R1');
pdecirc(0,2,1,'C1');
pdeellip(0,-2,1,1,...
0,'C2');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','R1-C1-C2')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(10,...
'neu',...
1,...
'0',...
'-cos(x).*x.*(2+cosh(y))-(y+2).*(sin(x).*sinh(y)+2*t.*y)')
pdesetbd(9,...
'neu',...
1,...
'0',...
'-cos(x).*x.*(2+cosh(y))-(y+2).*(sin(x).*sinh(y)+2*t.*y)')
pdesetbd(8,...
'neu',...
1,...
'0',...
'-cos(x).*x.*(2+cosh(y))-(y-2).*(sin(x).*sinh(y)+2*t.*y)')
pdesetbd(7,...
'neu',...
1,...
'0',...
'-cos(x).*x.*(2+cosh(y))-(y-2).*(sin(x).*sinh(y)+2*t.*y)')
pdesetbd(6,...
'dir',...
1,...
'1',...
'sin(x)*(2+cosh(2))+4*t')
pdesetbd(5,...
'dir',...
1,...
'1',...
'sin(x)*(2+cosh(2))+4*t')
pdesetbd(4,...
'dir',...
1,...
'1',...
'sin(x)*(2+cosh(2))+4*t')
pdesetbd(3,...
'dir',...
1,...
'1',...
'sin(x)*(2+cosh(2))+4*t')
pdesetbd(2,...
'dir',...
1,...
'1',...
'-sin(2)*(2+cosh(y))+(y.^2).*t')
pdesetbd(1,...
'dir',...
1,...
'1',...
'sin(2)*(2+cosh(y))+(y.^2).*t')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')
pdetool('refine')
pdetool('refine')
pdetool('refine')
pdetool('refine')

% PDE coefficients:
pdeseteq(2,...
'1.0',...
'0.0',...
'y.^2+2*sin(x)-2*t',...
'1.0',...
'0:0.01:3',...
'sin(x).*(2+cosh(y))',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['1.0              ';...
'0.0              ';...
'y.^2+2*sin(x)-2*t';...
'1.0              '])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','102912','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 1 1 0 0 0 301 1 0 1 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
